runtime: go111

handlers:
- url: /static/js
  static_dir: static/js

- url: /mybulma/css
  static_dir: mybulma/css

- url: /
  static_files: template/index.html
  upload: template/index.html
  #http_headers:
  #  Access-Control-Allow-Origin: https://anand-test.appspot.com

- url: /_ah/push-handlers/.*
  login: admin
  script: auto
  
- url: /_ah/get-handlers/.*
  # login: admin
  script: auto
  
- url: /.*
  # login: admin
  script: auto
  



